on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

env:
  site_demo_path: 'github_actions_branch_builds/${{ github.head_ref }}'

name: Create PR Build
jobs:
  create_or_update_pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Build Gatsby site
        run: DEPLOY_TO_SUBDIRECTORY="${{ env.site_demo_path }}" npm run build -- --prefix-paths
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          destination_dir: ${{ env.site_demo_path }}
