on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

env:
  site_demo_path: 'github_actions_branch_builds/${{ github.head_ref }}'

name: Create PR Build
jobs:
  create_or_update_pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Build Gatsby site
        run: DEPLOY_TO_SUBDIRECTORY="${{ env.site_demo_path }}" npm run build -- --prefix-paths
      - name: Deploy to Github Pages
        run: node ./node_modules/.bin/gh-pages --dist public --dest "${{ env.site_demo_path }}"
